### ISSUE TITLE
Gols can shoot passed columns

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustTcodTutorial#107] opened 2020-04-12 02:12 UTC
Columns should block the Gol's shot. 

It might be interesting if the Gol actually knocks down the column if they try to shoot the player through a column?

**Comment by nsmryan** [comment] 2020-04-14 13:30
@j0e1GMR  this should be fixed- monsters require a path to their target that is clear of obstacles and entities.

I didn't do anything about knocking over columns. Its definitely an interesting idea, although it makes columns very dangerous for the player.

**Comment by j0e1GMR** [comment] 2020-04-14 15:20
This is a good point, and may not be much fun. I can imagine moving to a pillar to push it over on a monster and then having it get pushed over on the player, which honestly should be a 1-hit kill. That would feel bad.

**Comment by nsmryan** [comment] 2020-06-25 01:01
Closing this issue as the problem is fixed, and I don't think we are making any additional changes right now on this thought.

**Closed by nsmryan** 2020-06-25 01:01 UTC
Labels: bug
