### ISSUE TITLE
Monster that has ranged attack

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustTcodTutorial#5] opened 2019-05-31 07:18 UTC
It would be cool to have a monster with a ranged attack, maybe vertical/horizontal or on diagonals, bishop or rook style.

**Comment by nsmryan** [comment] 2019-06-01 14:17
This ranged attack would be a shot right? Like, it would travel, get to its destination, and disappear?

This seems doable. I imagine a check during monster movement that if the player is in certain locations, to add an animation for a shot. The code to animate the shot should move it to the destination, and then if it hits the player to remove health.

**Comment by nsmryan** [comment] 2019-06-16 16:00
Monsters now have a "Reach" which is used in a field in the Object type called "attack".
This is used when taking a turn and gives the positions the monster can attack.

**Comment by nsmryan** [comment] 2019-06-16 16:28
the monsters now move to the closest valid position which can see the player and they can attack from.

I think the only thing not implemented here is an animation for ranged attacks. we can certainly add that to make it more clear what is going on.

**Comment by nsmryan** [comment] 2019-06-19 12:43
Added animations. I think this closes this issue- enemies can attack at range and move accordingly.

Commit closing the issue is: 9eb454ed1a66fa0da062925bdf09b91641ad9d38

**Closed by nsmryan** 2019-06-19 12:43 UTC
Labels: Idea
